# Generated by Django 2.2.1 on 2019-06-23 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Surveyor',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='Password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('questionType', models.CharField(max_length=50)),
                ('options', models.CharField(max_length=1000)),
                ('surveyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Surveyor'),
        ),
    ]
