# Generated by Django 2.2.1 on 2019-06-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='options',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
