# Generated by Django 2.2.1 on 2019-06-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_auto_20190623_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.Survey')),
            ],
        ),
    ]
