# Generated by Django 2.2.1 on 2019-06-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_surveyfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfile',
            name='file',
            field=models.FileField(default='none.php', upload_to=''),
        ),
    ]
