# Generated by Django 2.2.1 on 2019-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_surveyfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('maritalStatus', models.CharField(max_length=50)),
                ('familySize', models.IntegerField()),
                ('religion', models.CharField(max_length=50)),
                ('educationLevel', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('monthlyEarningRange', models.CharField(max_length=50)),
            ],
        ),
    ]
