# Generated by Django 2.2.1 on 2019-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0005_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='respondent',
            name='telephone',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
